### PR TITLE
Update Path in the main Readme

### PR DESCRIPTION
**Pull request by EagleoutIce**
The author name changed

### CODE REVIEW

**Comment by EagleoutIce** [comment]
Why did you close this? The current name is wrong and hence the command does not work:

```
> remotes::install_github("darwin-eu/PaRe")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`darwin-eu`) and repo name (`PaRe`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
> remotes::install_github("darwin-eu-dev/PaRe")
Downloading GitHub repo darwin-eu-dev/PaRe@HEAD
```

**Comment by mvankessel-EMC** [comment]
Yes you are correct. I reopened the PR. Once the actions finish I'll merge.

**Comment by EagleoutIce** [comment]
I updated the [README.Rmd](https://github.com/darwin-eu-dev/PaRe/blob/main/README.Rmd) and the base branch accordingly.

**Comment by EagleoutIce** [comment]
Now you've applied this change with https://github.com/darwin-eu-dev/PaRe/pull/59/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 as well. So this PR is no longer of need.

**Pull request closed without merging**
